apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notificationService.name }}
  labels:
    app: {{ .Values.notificationService.name }}
spec:
  selector:
    app: {{ .Values.notificationService.name }}
  ports:
    - port: {{ .Values.notificationService.portNumber }}
      targetPort: {{ .Values.notificationService.portNumber }}
      protocol: TCP
      name: {{ .Values.notificationService.name }}-web
  type: NodePort
