apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appPG.existingSecret }}
data:
  postgresql-password: {{ .Values.db.password}}
  DB_USER: {{ .Values.db.pgUsername}}
  DB_PASSWORD: {{ .Values.db.password}}


