kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-service-role
rules:
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-service-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-service-role
subjects:
  - kind: ServiceAccount
    name: app-service-account
    namespace: {{ .Release.Namespace }}